# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: afbe34f13d0fb7a8ed610cd06d99e6d4cd8b39a759214b4b6e452b7d53c1647f011daed0e17bbe10f65cb198149562f2a2023df3b79ac6178ee69a896bbb84b5

test:
  secret_key_base: bdf3eb1e0a09b7900c7e82034cedbec217b68b9f9c41cc7483445f4981d3f9a1855b463bb88434fb1f7da7f361fc6fce6b7e0a00797e6d3fb8e805b33fa49297

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
